services:
  check-image:
    container_name: hcmuit-thesis-check
    image: quay.io/sonnh-uit/hcmuit-thesis:dev
    volumes:
      - .:/uit-thesis:rw
    user: root
    environment:
      - IS_GLOSSARIES=1
    