services:
  my-thesis:
    container_name: dev-thesis-template
    image: quay.io/sonnh-uit/hcmuit-thesis:dev
    volumes:
      - .:/app
  slide:
    build:
      context: presentation
      dockerfile: Dockerfile
    volumes:
      - ./presentation:/app
