name: Build document 
on:
  push:
    branches: ["dev"]
jobs:
  apps_script_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install latex
        run: sudo apt-get install -y texlive-full texlive-latex-extra texlive-lang-all texlive-publishers texlive-bibtex-extra biber 
      - name: Build thesis
        run: pdflatex thesis && biber thesis && makeglossaries thesis && pdflatex thesis && pdflatex thesis
      # - name: Compile LaTeX document
      #   uses: xu-cheng/latex-action@v3
      #   with:
      #     root_file: thesis.tex
      - name: Upload PDF file
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          overwrite: true
          retention-days: 7
          name: final-thesis
          path: thesis.pdf
      - name: Print url to down load file
        run:  echo 'Download url is ${{ steps.artifact-upload-step.outputs.artifact-url }}'